// SYNTAX TEST "source.dbml" "Numbers and color literals"

Table t [headercolor: #336699] {
//                    ^^^^^^^ constant.other.color.dbml
  id int [default: 42]
//                 ^^ constant.numeric.dbml
  price decimal [default: 9.99]
//                        ^^^^ constant.numeric.dbml
}
